### ISSUE TITLE
JupyterHub image with globus

### ISSUE THREAD

**Issue by zonca** [cheapandfair/globus-jupyter-notebook#2]
@rpwagner it should appear in 10 minutes here tagged with today's date:

https://github.com/cheapandfair/globus-jupyter-notebook/pkgs/container/globus-jupyter-notebook

**Comment by zonca** [comment]
@rpwagner it is probably useful to have a private repo here with the configuration of your jupyterhub instance, so we have it saved for future tutorials.

**Comment by rpwagner** [comment]
@zonca can you change the settings so that the published image is public? I've configured the JupyterHub instance to add the image as an option but packages for this repo aren't public.

**Comment by rpwagner** [comment]
> @rpwagner it is probably useful to have a private repo here with the configuration of your jupyterhub instance, so we have it saved for future tutorials.

Agreed. We can have a separate repo just for those kinds of notes, etc.

**Comment by zonca** [comment]
> @zonca can you change the settings so that the published image is public? I've configured the JupyterHub instance to add the image as an option but packages for this repo aren't public.

ok, try now

**Comment by rpwagner** [comment]
Working!

Currently set to pull the latest image. We can start using tags when we're closer.

<img width="543" alt="Screenshot 2024-09-13 at 4 25 10 PM" src="https://github.com/user-attachments/assets/7caefe07-37f0-42ce-b68b-128d85e8c2dd">
<img width="541" alt="Screenshot 2024-09-13 at 4 24 42 PM" src="https://github.com/user-attachments/assets/6a82d5eb-1149-4c71-9f2c-16068c240b89">
<img width="896" alt="Screenshot 2024-09-13 at 4 24 04 PM" src="https://github.com/user-attachments/assets/59e064f1-88f6-4f08-8843-97716f1eae1b">

**Comment by rpwagner** [comment]
> @rpwagner it is probably useful to have a private repo here with the configuration of your jupyterhub instance, so we have it saved for future tutorials.

@zonca I set this up in a new [planning](https://github.com/cheapandfair/planning) repo. We can also use that for developing the lesson plan, etc. I.e., a place to coordinate things across these repositories.
